// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0GaJlfJN4S1Y8Nre1iC4bWNV4Cq-8NrA',
    appId: '1:353806653645:web:a4d0958efc57212606b184',
    messagingSenderId: '353806653645',
    projectId: 'fetch-animalapi',
    authDomain: 'fetch-animalapi.firebaseapp.com',
    storageBucket: 'fetch-animalapi.firebasestorage.app',
    measurementId: 'G-NDNWNX07H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVU4Dqz9kvElz104LUywjyZxOi4PAMlPc',
    appId: '1:353806653645:android:cded4d58e89c22a006b184',
    messagingSenderId: '353806653645',
    projectId: 'fetch-animalapi',
    storageBucket: 'fetch-animalapi.firebasestorage.app',
  );
}
